// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euyyqyjjcrxlgbjekdnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1eXlxeWpqY3J4bGdiamVrZG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzU0NDgsImV4cCI6MjA2MzgxMTQ0OH0.tu6FhkFgTQ6I_pTlnGroMODqgjEIv9yS_lXaxQluv6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);